import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Services Me Website",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png", // Correct path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        data-gptw=""
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
